routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get("store", "ItemController@index")->name("store");
Route::resource("item", "ItemController");
Route::middleware("auth")->group(function () {
    Route::resource("order", "OrderController");
    Route::post("order/compute", "OrderController@computeOrder")->name("order.compute");
});

Route::get("/.well-known/acme-challenge/oTJciIAPt2mOcRjcJqG0GikbvfdyYRuPE94B5ZoNY-c", function () {
    return "oTJciIAPt2mOcRjcJqG0GikbvfdyYRuPE94B5ZoNY-c.ebuo2KIon8xkwLbJbGWw5EhnHMxJUl_8a_VrOjBJfjg";
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    Orders
                    <a class="btn btn-primary" href="{{ route("store") }}">Go to Store</a>
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="row">
                        @if(count(Auth::user()->orders) > 0)
                            @foreach(Auth::user()->orders as $order)
                                <div class="col-12 col-md-4 mb-3">
                                    <a href="{{ route("order.show", $order->id) }}" class="reset-link">
                                        <div class="card h-100 home__order">
                                            <div class="card-body text-center">
                                                    <h5 class="card-title">Order# {{ $order->id }}</h5>
                                                    <ul class="list-group">
                                                        @foreach($order->items as $item)
                                                            <li class="list-group-item list-group-item-primary">
                                                                {{ $item->name }}
                                                            </li>
                                                        @endforeach
                                                    </ul>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            @endforeach
                        @else
                            <div class="col">
                                <a href="{{ route("store") }}">Start ordering now!</a>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection